kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: consumer-hpa
  namespace: sink
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: sink

  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      policies:
        - type: Pods
          periodSeconds: 5
          value: 4
    scaleDown:
      stabilizationWindowSeconds: 1
      policies:
        - type: Pods
          periodSeconds: 5
          value: 4
  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumergroup_lag
        selector:
          matchLabels:
            topic: mm3.k2.testdb.accounts
            consumergroup: connect-sink-test-connector
      target:
        type: Value
        averageValue: 10