---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-prometheus-adapter
  namespace: monitoring
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    externalRules:
    - seriesQuery: 'kafka_consumergroup_lag'
      resources:
        template: <<.Resource>>
      name:
        matches: kafka_consumergroup_lag
        as: kafka_consumergroup_lag
      metricsQuery: 'avg_over_time(kafka_consumergroup_lag_sum{topic="mm3.k2.testdb.accounts", consumergroup="connect-sink-test-connector"}[1m])'