apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter
        command:
          - kafka_exporter
          - "--kafka.server=10.44.0.1:9092"
          - "--kafka.server=10.42.0.1:9092"
          - "--kafka.server=10.36.0.2:9092"
          - "--kafka.server=10.42.0.4:9093"
          - "--kafka.server=10.36.0.5:9093"
          - "--kafka.server=10.44.0.5:9093"                              
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP
