apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: monitoring
  
spec:
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 9308
  selector:
    app: kafka-exporter