apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  serviceName: kafka-exporter
  updateStrategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      restartPolicy: Always
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter
        command:
          - kafka_exporter
          - "--kafka.server=kafka-consumer-0.kafka-service.kafka-con.svc.cluster.local:9093"
          - "--kafka.server=kafka-consumer-1.kafka-service.kafka-con.svc.cluster.local:9093"
          - "--kafka.server=kafka-consumer-2.kafka-service.kafka-con.svc.cluster.local:9093"
          - "--kafka.server=kafka-broker-0.kafka-service.kafka.svc.cluster.local:9092"
          - "--kafka.server=kafka-broker-1.kafka-service.kafka.svc.cluster.local:9092"
          - "--kafka.server=kafka-broker-2.kafka-service.kafka.svc.cluster.local:9092" 
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP
