apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://10.36.0.5:8086
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: test