FROM debezium/connect
# FROM wurstmeister/kafka

COPY confluentinc-kafka-connect-jdbc-10.6.0 /kafka/connect

COPY mysql-connector-java-8.0.30.jar /kafka/libs

# COPY debezium-connector-mysql /kafka/connect