apiVersion: v1

datasources:
- name: Analysis Server
  orgId: 1
  type: influxdb
  access: proxy
  url: http://10.100.61.131:8086
  database: telegraf
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: test
- name: Gatling
  orgId: 1
  type: influxdb
  access: proxy
  url: http://10.100.61.131:8086
  database: telegraf
  isDefault: true
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: user
  basicAuthPassword: test