apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb-data
  name: influxdb-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: inf-pv
  resources:
    requests:
      storage: 5Gi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inf-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: 'inf-pv'
  hostPath:
    path: /data/
    type: DirectoryOrCreate